apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-spark-app
  template:
    metadata:
      labels:
        app: traffic-spark-app
    spec:
      containers:
        - name: spark-processor
          image: laidung/traffic-spark-app:v17
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: KAFKA_BROKER
              value: "my-kafka:9092"
            - name: TOPIC_NAME
              value: "traffic_data"
            # ĐÃ SỬA: Thay đổi hostname sang my-mongodb (khớp với kết quả get svc)
            - name: MONGO_URI
              value: "mongodb://root:bigdataproject@my-mongodb.default.svc.cluster.local:27017/traffic_db?authSource=admin"
            - name: MONGO_DATABASE
              value: "traffic_db"
            - name: MONGO_COLLECTION
              value: "insights"
            - name: SPARK_MASTER
              value: "local[*]"